version: '3.9'

services:
  backend:
    build: .
    ports:
      - 3001:3001
    restart: unless-stopped

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./deploy/nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/ssl:/etc/ssl
